### ISSUE TITLE
[suggestion] mobile: make the column with filters sticky

### ISSUE THREAD

**Issue by MaryLevchuk** [dmtrglvk/aeroSALES#10]
If we sure that we want to have horizontal tables on Dashboard, Seat Factor, R'Ask by day pages, then it makes probably sense to make the first left table column (with row names, filter names) sticky. Because when I scroll to the end of the table I can see only numbers without their meaning.

**Comment by dmtrglvk** [comment]
Agree but let's hear what business think about it. Probably we will do that soon.
