### ISSUE TITLE
[design clarification] mobile, Dashboard: Seat Factor table - missed set of filters

### ISSUE THREAD

**Issue by MaryLevchuk** [dmtrglvk/aeroSALES#11]
Design: for the desktop on Dashboard page on Seat Factor table (the last table) we have set of filters by month 
![2017-08-13_11h51_49](https://user-images.githubusercontent.com/6398035/29248331-0070f3a0-801e-11e7-85d7-dba4aa99883b.png)
but for mobile they are missed. Do we really not need them?

**Comment by dmtrglvk** [comment]
Developed according to design. Nothing to do here for me 😄
