### ISSUE TITLE
desktop, R'Ask by Day: different number of levels in breadcrumbs 

### ISSUE THREAD

**Issue by MaryLevchuk** [dmtrglvk/aeroSALES#13]
Design: 
![2017-08-13_12h03_13](https://user-images.githubusercontent.com/6398035/29248372-675d3b2c-801f-11e7-94cc-fbb6fe4245d7.png)
Actual page: 
![2017-08-13_12h03_55](https://user-images.githubusercontent.com/6398035/29248375-7f47f452-801f-11e7-833a-1173f27ac1e9.png)

**Comment by dmtrglvk** [comment]
Developed only to show how it will look. This isn't important in markup.
