### ISSUE TITLE
desktop, Seat Factor: cut filter names

### ISSUE THREAD

**Issue by MaryLevchuk** [dmtrglvk/aeroSALES#15]
Design: 
![2017-08-13_12h21_50](https://user-images.githubusercontent.com/6398035/29248480-004a41a2-8022-11e7-8c66-117d594d7e64.png)
Actual page: 
![2017-08-13_12h22_20](https://user-images.githubusercontent.com/6398035/29248486-126f3360-8022-11e7-9c2f-90c29da77eaa.png)

The same goes to all filters on this page: all the names should be shown totally and the filters should be uniformly stretched to the whole width of the page.

**Comment by dmtrglvk** [comment]
I'm not sure we will do that. Filter were developer according with dashboard page. If I increase width they will drop to the next line on desktop.
