### ISSUE TITLE
mobile, Dashboard: one active checkbox left after page refresh

### ISSUE THREAD

**Issue by MaryLevchuk** [dmtrglvk/aeroSALES#2]
1) When I opened Dashboard page there was checked one checkbox '30' ;
2) I made all check boxes checked;
3) Refreshed the page.
Actual: three from four check boxes were unmarked, and only '30' left checked.
Expected: all check boxes are unmarked (or all are still checked).

**Comment by dmtrglvk** [comment]
Developed according to design. In our mocked markup we tried to show, how checked element will look, so leaved only one checked. Will be unchecked in real "implementd" version.
