### ISSUE TITLE
mobile, Dashboard: inaccuracies on dropdowns that are before graphs

### ISSUE THREAD

**Issue by MaryLevchuk** [dmtrglvk/aeroSALES#4]
1) adjust text and arrows on 'Last 24 hours' and 'My queries' dropdowns;
2) Cut filter names on mobile and on the desktop:
![2017-08-13_12h28_39](https://user-images.githubusercontent.com/6398035/29248527-f4ec3dbe-8022-11e7-8e8c-53dcca4c9288.png)

3) Make left align for the text in dropdown options.

**Comment by dmtrglvk** [comment]
Fixed
