### ISSUE TITLE
mobile, Dashboard: wrong captions on Y axis on Top Stations chart

### ISSUE THREAD

**Issue by MaryLevchuk** [dmtrglvk/aeroSALES#8]
Actual: numbers 0 ... 800
Expected: SHJ, BLR, BOM, CMB, KTM

The same in desktop version

**Comment by dmtrglvk** [comment]
This was disscussed with PM and approved. According to D3js lib we should have two numbers (for X and Y axe) and we can build the point. If we will have letter, instead of number, D3 won't be able to count the place coordinates, where that point should be.
